page 50386 "NRS E-Invoices"
{
    Caption = 'NRS E-Invoices';
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = "NRS IRN Log";
    CardPageId = "NRS E-Invoice Card";
    Editable = true;
    SourceTableView = sorting("Entry No.") order(descending);

    layout
    {
        area(Content)
        {
            repeater(Invoices)
            {
                field("Document No."; Rec."Document No.")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the posted sales invoice number.';
                }
                field("Job No."; JobNo)
                {
                    Caption = 'Job No.';
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the Job No. from the posted document.';
                }
                field("Customer No."; CustomerNo)
                {
                    Caption = 'Customer No.';
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the customer number from the posted document.';
                }
                field("Customer Name"; CustomerName)
                {
                    Caption = 'Customer Name';
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the customer name from the posted document.';
                }
                field(IRN; Rec.IRN)
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the Invoice Reference Number returned by NRS.';
                }
                field(Status; Rec.Status)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the IRN status. You can override it here.';
                    StyleExpr = StatusStyle;

                    trigger OnValidate()
                    begin
                        Rec.SyncStatusToDocument();
                    end;
                }
                field("Validation Status"; Rec."Validation Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the validation status. You can override it here.';
                }

                field(payment_status; Rec."Payment Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the payment status. You can override it here.';
                }
                field("Posting Date"; Rec."Posting Date")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the invoice posting/issuance date.';
                }
                field("Invoice Number"; Rec."Invoice Number")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the invoice_number sent to NRS.';
                }
                field("Has QR Code"; Rec."Has QR Code")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies whether a QR code has been generated.';
                }
                field("Response Message"; Rec."Response Message")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the latest message from the NRS service.';
                }
                field("Generated At"; Rec."Generated At")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies when the IRN was generated.';
                }
                field("Generated By"; Rec."Generated By")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies who generated the IRN.';
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(ViewReport)
            {
                ApplicationArea = All;
                Caption = 'View Invoice Report';
                ToolTip = 'Previews/prints the NRS e-invoice report, including the QR code.';
                Image = Print;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;
                visible = false;
                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                begin
                    SalesInvHeader.SetRange("No.", Rec."Document No.");
                    Report.Run(Report::"NRS E-Invoice", true, false, SalesInvHeader);
                end;
            }
            action(OpenPostedInvoice)
            {
                ApplicationArea = All;
                Caption = 'Open Posted Invoice';
                ToolTip = 'Opens the underlying posted sales invoice.';
                Image = Invoice;

                trigger OnAction()
                begin
                    Rec.ShowDocument();
                end;
            }
            action(GenerateIRN)
            {
                ApplicationArea = All;
                Caption = 'Generate IRN';
                ToolTip = 'Generates (or re-generates) the IRN for this invoice.';
                Image = SendElectronicDocument;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                    EInvoiceMgt: Codeunit "NRS E-Invoice Mgt.";
                begin
                    if Rec."Source Table No." <> Database::"Sales Invoice Header" then
                        exit;
                    if SalesInvHeader.Get(Rec."Document No.") then
                        EInvoiceMgt.GenerateForInvoice(SalesInvHeader, true);
                    CurrPage.Update(false);
                end;
            }
            action(ValidateInvoice)
            {
                ApplicationArea = All;
                Caption = 'Validate';
                ToolTip = 'Validates this invoice against NRS.';
                Image = CheckList;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                    ValidateMgt: Codeunit "NRS Validate Invoice Mgt.";
                begin
                    if Rec."Source Table No." <> Database::"Sales Invoice Header" then
                        exit;
                    if SalesInvHeader.Get(Rec."Document No.") then
                        ValidateMgt.ValidateForInvoice(SalesInvHeader);
                    CurrPage.Update(false);
                end;
            }
            action(UpdatePaymentStatusBulk)
            {
                ApplicationArea = All;
                Caption = 'Update Payment Status';
                ToolTip = 'Reports a payment status change (PAID, REJECTED or PARTIAL) to NRS for all the selected invoices at once.';
                Image = Payment;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                var
                    IRNLog: Record "NRS IRN Log";
                    EInvoiceMgt: Codeunit "NRS E-Invoice Mgt.";
                    PayPage: Page "NRS Payment Update";
                    StatusText: Text;
                    Reference: Text;
                    Amount: Decimal;
                    TotalCount: Integer;
                    OkCount: Integer;
                    FailCount: Integer;
                    SkipCount: Integer;
                    NothingTxt: Label 'No invoices were selected.';
                    ConfirmTxt: Label 'Update the NRS payment status for %1 selected invoice(s)?', Comment = '%1 = count';
                    SummaryTxt: Label 'Payment status update complete.\\Processed: %1\Updated: %2\Failed: %3\Skipped (no IRN): %4', Comment = '%1..%4 counts';
                begin
                    CurrPage.SetSelectionFilter(IRNLog);
                    if IRNLog.IsEmpty() then begin
                        Message(NothingTxt);
                        exit;
                    end;

                    if not Confirm(ConfirmTxt, false, IRNLog.Count()) then
                        exit;

                    // Ask once for the status/amount/note; it is applied to every selected invoice.
                    if PayPage.RunModal() <> Action::OK then
                        exit;
                    StatusText := PayPage.GetStatusText();
                    Amount := PayPage.GetAmount();
                    Reference := PayPage.GetReference();

                    IRNLog.FindSet();
                    repeat
                        TotalCount += 1;
                        if IRNLog.IRN = '' then
                            SkipCount += 1
                        else
                            if EInvoiceMgt.UpdatePaymentStatus(IRNLog.IRN, StatusText, Amount, Reference) then
                                OkCount += 1
                            else
                                FailCount += 1;
                    until IRNLog.Next() = 0;

                    Message(SummaryTxt, TotalCount, OkCount, FailCount, SkipCount);
                    CurrPage.Update(false);
                end;
            }
        }
    }

    var
        StatusStyle: Text;
        JobNo: Code[20];
        CustomerNo: Code[20];
        CustomerName: Text[100];

    trigger OnAfterGetRecord()
    begin
        case Rec.Status of
            Rec.Status::Generated:
                StatusStyle := 'Favorable';
            Rec.Status::Failed:
                StatusStyle := 'Unfavorable';
            Rec.Status::Duplicate:
                StatusStyle := 'Ambiguous';
            else
                StatusStyle := 'Standard';
        end;

        PopulateDocInfo();
    end;

    /// <summary>Looks up the customer and job for the row from the underlying posted document.</summary>
    local procedure PopulateDocInfo()
    var
        SalesInvHeader: Record "Sales Invoice Header";
        CrMemoHeader: Record "Sales Cr.Memo Header";
    begin
        Clear(JobNo);
        Clear(CustomerNo);
        Clear(CustomerName);

        case Rec."Source Table No." of
            Database::"Sales Invoice Header":
                if SalesInvHeader.Get(Rec."Document No.") then begin
                    CustomerNo := SalesInvHeader."Sell-to Customer No.";
                    CustomerName := CopyStr(SalesInvHeader."Sell-to Customer Name", 1, MaxStrLen(CustomerName));
                    JobNo := SalesInvHeader."Job No.";
                end;
            Database::"Sales Cr.Memo Header":
                if CrMemoHeader.Get(Rec."Document No.") then begin
                    CustomerNo := CrMemoHeader."Sell-to Customer No.";
                    CustomerName := CopyStr(CrMemoHeader."Sell-to Customer Name", 1, MaxStrLen(CustomerName));
                    JobNo := CrMemoHeader."Job No.";
                end;
        end;
    end;
}
