page 50386 "NRS E-Invoices"
{
    Caption = 'NRS E-Invoices';
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = "NRS IRN Log";
    CardPageId = "NRS E-Invoice Card";
    Editable = true;
    SourceTableView = sorting("Entry No.") order(descending);

    layout
    {
        area(Content)
        {
            repeater(Invoices)
            {
                field("Document No."; Rec."Document No.")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the posted sales invoice number.';
                }
                field(IRN; Rec.IRN)
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the Invoice Reference Number returned by NRS.';
                }
                field(Status; Rec.Status)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the IRN status. You can override it here.';
                    StyleExpr = StatusStyle;

                    trigger OnValidate()
                    begin
                        Rec.SyncStatusToDocument();
                    end;
                }
                field("Validation Status"; Rec."Validation Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the validation status. You can override it here.';
                }
                field("Posting Date"; Rec."Posting Date")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the invoice posting/issuance date.';
                }
                field("Invoice Number"; Rec."Invoice Number")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the invoice_number sent to NRS.';
                }
                field("Has QR Code"; Rec."Has QR Code")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies whether a QR code has been generated.';
                }
                field("Response Message"; Rec."Response Message")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies the latest message from the NRS service.';
                }
                field("Generated At"; Rec."Generated At")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies when the IRN was generated.';
                }
                field("Generated By"; Rec."Generated By")
                {
                    ApplicationArea = All;
                    Editable = false;
                    ToolTip = 'Specifies who generated the IRN.';
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(ViewReport)
            {
                ApplicationArea = All;
                Caption = 'View Invoice Report';
                ToolTip = 'Previews/prints the NRS e-invoice report, including the QR code.';
                Image = Print;
                Promoted = true;
                PromotedCategory = Process;
                PromotedOnly = true;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                begin
                    SalesInvHeader.SetRange("No.", Rec."Document No.");
                    Report.Run(Report::"NRS E-Invoice", true, false, SalesInvHeader);
                end;
            }
            action(OpenPostedInvoice)
            {
                ApplicationArea = All;
                Caption = 'Open Posted Invoice';
                ToolTip = 'Opens the underlying posted sales invoice.';
                Image = Invoice;

                trigger OnAction()
                begin
                    Rec.ShowDocument();
                end;
            }
            action(GenerateIRN)
            {
                ApplicationArea = All;
                Caption = 'Generate IRN';
                ToolTip = 'Generates (or re-generates) the IRN for this invoice.';
                Image = SendElectronicDocument;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                    EInvoiceMgt: Codeunit "NRS E-Invoice Mgt.";
                begin
                    if Rec."Source Table No." <> Database::"Sales Invoice Header" then
                        exit;
                    if SalesInvHeader.Get(Rec."Document No.") then
                        EInvoiceMgt.GenerateForInvoice(SalesInvHeader, true);
                    CurrPage.Update(false);
                end;
            }
            action(ValidateInvoice)
            {
                ApplicationArea = All;
                Caption = 'Validate';
                ToolTip = 'Validates this invoice against NRS.';
                Image = CheckList;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                    ValidateMgt: Codeunit "NRS Validate Invoice Mgt.";
                begin
                    if Rec."Source Table No." <> Database::"Sales Invoice Header" then
                        exit;
                    if SalesInvHeader.Get(Rec."Document No.") then
                        ValidateMgt.ValidateForInvoice(SalesInvHeader);
                    CurrPage.Update(false);
                end;
            }
        }
    }

    var
        StatusStyle: Text;

    trigger OnAfterGetRecord()
    begin
        case Rec.Status of
            Rec.Status::Generated:
                StatusStyle := 'Favorable';
            Rec.Status::Failed:
                StatusStyle := 'Unfavorable';
            Rec.Status::Duplicate:
                StatusStyle := 'Ambiguous';
            else
                StatusStyle := 'Standard';
        end;
    end;
}
