table 50181 "NRS IRN Log"
{
    Caption = 'NRS IRN Log';
    DataClassification = CustomerContent;
    LookupPageId = "NRS IRN Log";
    DrillDownPageId = "NRS IRN Log";

    fields
    {
        field(1; "Entry No."; Integer)
        {
            Caption = 'Entry No.';
            AutoIncrement = true;
        }
        field(2; "Source Table No."; Integer)
        {
            Caption = 'Source Table No.';
        }
        field(3; "Document No."; Code[20])
        {
            Caption = 'Document No.';
        }
        field(4; "Posting Date"; Date)
        {
            Caption = 'Posting Date';
        }
        field(5; "Invoice Number"; Text[100])
        {
            Caption = 'Invoice Number';
        }
        field(6; "Business ID"; Text[100])
        {
            Caption = 'Business ID';
        }
        field(7; "Service ID"; Text[50])
        {
            Caption = 'Service ID';
        }
        field(8; IRN; Text[100])
        {
            Caption = 'IRN';
        }
        field(9; Status; Enum "NRS IRN Status")
        {
            Caption = 'Status';
        }
        field(10; "Response Message"; Text[250])
        {
            Caption = 'Response Message';
        }
        field(11; "Error Message"; Text[2048])
        {
            Caption = 'Error Message';
        }
        field(12; "HTTP Status Code"; Integer)
        {
            Caption = 'HTTP Status Code';
        }
        field(13; "Attempts"; Integer)
        {
            Caption = 'Attempts';
        }
        field(14; "Generated At"; DateTime)
        {
            Caption = 'Generated At';
        }
        field(15; "Generated Date"; Date)
        {
            Caption = 'Generated Date';
        }
        field(16; "Generated By"; Code[50])
        {
            Caption = 'Generated By';
            TableRelation = User."User Name";
            ValidateTableRelation = false;
        }
        field(20; "QR Code Base64"; Blob)
        {
            Caption = 'QR Code (Base64)';
        }
        field(21; "QR Generated At"; DateTime)
        {
            Caption = 'QR Generated At';
        }
        field(22; "Has QR Code"; Boolean)
        {
            Caption = 'Has QR Code';
            Editable = false;
        }
        field(30; "Validation Status"; Enum "NRS Validation Status")
        {
            Caption = 'Validation Status';
        }
        field(31; "Validation Message"; Text[250])
        {
            Caption = 'Validation Message';
        }
        field(32; "Validated At"; DateTime)
        {
            Caption = 'Validated At';
        }
        field(33; "Request Body"; Blob)
        {
            Caption = 'Request Body';
        }
    }

    keys
    {
        key(PK; "Entry No.")
        {
            Clustered = true;
        }
        key(Document; "Source Table No.", "Document No.")
        {
        }
        key(Status; Status, "Generated Date")
        {
        }
    }

    fieldgroups
    {
        fieldgroup(DropDown; "Document No.", IRN, Status)
        {
        }
    }

    /// <summary>Stamps user/time fields for the current attempt.</summary>
    procedure StampAudit()
    begin
        "Attempts" += 1;
        "Generated At" := CurrentDateTime();
        "Generated Date" := DT2Date(CurrentDateTime());
        "Generated By" := CopyStr(UserId(), 1, MaxStrLen("Generated By"));
    end;

    procedure SetQRCode(Base64Value: Text)
    var
        OutStr: OutStream;
    begin
        Clear("QR Code Base64");
        if Base64Value = '' then
            exit;
        "QR Code Base64".CreateOutStream(OutStr, TextEncoding::UTF8);
        OutStr.Write(Base64Value);
    end;

    procedure GetQRCode(): Text
    var
        InStr: InStream;
        Result: Text;
    begin
        CalcFields("QR Code Base64");
        if not "QR Code Base64".HasValue() then
            exit('');
        "QR Code Base64".CreateInStream(InStr, TextEncoding::UTF8);
        InStr.ReadText(Result);
        exit(Result);
    end;

    /// <summary>Stores the exact JSON request body sent to NRS (for diagnostics).</summary>
    procedure SetRequestBody(BodyText: Text)
    var
        OutStr: OutStream;
    begin
        Clear("Request Body");
        if BodyText = '' then
            exit;
        "Request Body".CreateOutStream(OutStr, TextEncoding::UTF8);
        OutStr.Write(BodyText);
    end;

    /// <summary>Reads back the last JSON request body sent to NRS.</summary>
    procedure GetRequestBody() Result: Text
    var
        InStr: InStream;
        Line: Text;
    begin
        CalcFields("Request Body");
        if not "Request Body".HasValue() then
            exit('');
        "Request Body".CreateInStream(InStr, TextEncoding::UTF8);
        while not InStr.EOS() do begin
            InStr.ReadText(Line);
            Result += Line;
        end;
    end;

    /// <summary>Pushes a manually changed status/IRN back onto the linked posted sales invoice.</summary>
    procedure SyncStatusToDocument()
    var
        SalesInvHeader: Record "Sales Invoice Header";
    begin
        if "Source Table No." <> Database::"Sales Invoice Header" then
            exit;
        if not SalesInvHeader.Get("Document No.") then
            exit;
        SalesInvHeader."NRS IRN" := CopyStr(IRN, 1, MaxStrLen(SalesInvHeader."NRS IRN"));
        SalesInvHeader."NRS IRN Status" := Status;
        SalesInvHeader.Modify(false);
    end;

    /// <summary>Opens the source document behind this log entry, when it is a Sales Invoice Header.</summary>
    procedure ShowDocument()
    var
        SalesInvHeader: Record "Sales Invoice Header";
    begin
        if "Source Table No." <> Database::"Sales Invoice Header" then
            exit;
        if not SalesInvHeader.Get("Document No.") then
            exit;
        Page.Run(Page::"Posted Sales Invoice", SalesInvHeader);
    end;
}
