page 50396 "NRS IRN Log"
{
    Caption = 'NRS IRN Log';
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = "NRS IRN Log";
    Editable = false;
    SourceTableView = sorting("Entry No.") order(descending);

    layout
    {
        area(Content)
        {
            repeater(Entries)
            {
                field("Document No."; Rec."Document No.")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the source document (e.g. the posted sales invoice number).';

                    trigger OnDrillDown()
                    begin
                        Rec.ShowDocument();
                    end;
                }
                field(Status; Rec.Status)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the outcome of the IRN generation attempt.';
                    StyleExpr = StatusStyle;
                }
                field(IRN; Rec.IRN)
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the Invoice Reference Number returned by NRS.';
                }
                field("Posting Date"; Rec."Posting Date")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the invoice posting/issuance date.';
                }
                field("Invoice Number"; Rec."Invoice Number")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the invoice_number value sent to NRS.';
                }
                field("Response Message"; Rec."Response Message")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the message returned by the NRS service.';
                }
                field("HTTP Status Code"; Rec."HTTP Status Code")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the HTTP status code returned by the service.';
                }
                field("Validation Status"; Rec."Validation Status")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies whether the invoice passed NRS validation.';
                }
                field("Validation Message"; Rec."Validation Message")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the message returned by the validate endpoint.';
                }
                field("Validated At"; Rec."Validated At")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies when the invoice was last validated.';
                }
                field("Error Message"; Rec."Error Message")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies the error detail when the attempt did not succeed.';
                }
                field("Attempts"; Rec."Attempts")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies how many times generation has been attempted for this document.';
                }
                field("Generated At"; Rec."Generated At")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies when the most recent attempt ran.';
                }
                field("Generated By"; Rec."Generated By")
                {
                    ApplicationArea = All;
                    ToolTip = 'Specifies who ran the most recent attempt.';
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(RetryFailed)
            {
                ApplicationArea = All;
                Caption = 'Retry';
                ToolTip = 'Retries IRN generation for the selected failed document.';
                Image = Retry;

                trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                    EInvoiceMgt: Codeunit "NRS E-Invoice Mgt.";
                begin
                    if Rec."Source Table No." <> Database::"Sales Invoice Header" then
                        exit;
                    if not SalesInvHeader.Get(Rec."Document No.") then
                        exit;
                    EInvoiceMgt.GenerateForInvoice(SalesInvHeader, true);
                    CurrPage.Update(false);
                end;
            }
            action(ShowDoc)
            {
                ApplicationArea = All;
                Caption = 'Show Document';
                ToolTip = 'Opens the source document for this entry.';
                Image = Document;

                trigger OnAction()
                begin
                    Rec.ShowDocument();
                end;
            }
        }
    }

    var
        StatusStyle: Text;

    trigger OnAfterGetRecord()
    begin
        case Rec.Status of
            Rec.Status::Generated:
                StatusStyle := 'Favorable';
            Rec.Status::Failed:
                StatusStyle := 'Unfavorable';
            Rec.Status::Duplicate:
                StatusStyle := 'Ambiguous';
            else
                StatusStyle := 'Standard';
        end;
    end;
}
