codeunit 50182 "NRS Reference Data"
{
    // Seeds the NRS reference tables. States are the standard ISO 3166-2:NG codes (NG-XX),
    // which match the codes NRS uses. LGAs must be loaded from the NRS LGA code list.

    Permissions = tabledata "NRS State" = RIMD,
                  tabledata "NRS LGA" = RIMD;

    /// <summary>Inserts the 36 states and the FCT (idempotent - existing rows are left as-is).</summary>
    procedure SeedNigerianStates()
    begin
        AddState('NG-AB', 'Abia');
        AddState('NG-AD', 'Adamawa');
        AddState('NG-AK', 'Akwa Ibom');
        AddState('NG-AN', 'Anambra');
        AddState('NG-BA', 'Bauchi');
        AddState('NG-BY', 'Bayelsa');
        AddState('NG-BE', 'Benue');
        AddState('NG-BO', 'Borno');
        AddState('NG-CR', 'Cross River');
        AddState('NG-DE', 'Delta');
        AddState('NG-EB', 'Ebonyi');
        AddState('NG-ED', 'Edo');
        AddState('NG-EK', 'Ekiti');
        AddState('NG-EN', 'Enugu');
        AddState('NG-GO', 'Gombe');
        AddState('NG-IM', 'Imo');
        AddState('NG-JI', 'Jigawa');
        AddState('NG-KD', 'Kaduna');
        AddState('NG-KN', 'Kano');
        AddState('NG-KT', 'Katsina');
        AddState('NG-KE', 'Kebbi');
        AddState('NG-KO', 'Kogi');
        AddState('NG-KW', 'Kwara');
        AddState('NG-LA', 'Lagos');
        AddState('NG-NA', 'Nasarawa');
        AddState('NG-NI', 'Niger');
        AddState('NG-OG', 'Ogun');
        AddState('NG-ON', 'Ondo');
        AddState('NG-OS', 'Osun');
        AddState('NG-OY', 'Oyo');
        AddState('NG-PL', 'Plateau');
        AddState('NG-RI', 'Rivers');
        AddState('NG-SO', 'Sokoto');
        AddState('NG-TA', 'Taraba');
        AddState('NG-YO', 'Yobe');
        AddState('NG-ZA', 'Zamfara');
        AddState('NG-FC', 'Federal Capital Territory');
    end;

    /// <summary>Adds (or updates the name of) a single LGA. Used when importing the NRS LGA list.</summary>
    procedure AddLGA(LgaCode: Code[20]; LgaName: Text[100]; StateCode: Code[10])
    var
        LGA: Record "NRS LGA";
    begin
        if LgaCode = '' then
            exit;
        if not LGA.Get(LgaCode) then begin
            LGA.Init();
            LGA.Code := LgaCode;
            LGA.Insert();
        end;
        LGA.Name := LgaName;
        LGA."State Code" := StateCode;
        LGA.Modify();
    end;

    local procedure AddState(StateCode: Code[10]; StateName: Text[100])
    var
        State: Record "NRS State";
    begin
        if State.Get(StateCode) then
            exit;
        State.Init();
        State.Code := StateCode;
        State.Name := StateName;
        State.Insert();
    end;

    /// <summary>Inserts all NRS LGAs (idempotent). Split into chunks to keep each method small.</summary>
    procedure SeedNigerianLGAs()
    begin
        SeedLGAChunk1();
        SeedLGAChunk2();
        SeedLGAChunk3();
        SeedLGAChunk4();
        SeedLGAChunk5();
        SeedLGAChunk6();
        SeedLGAChunk7();
    end;

    local procedure SeedLGAChunk1()
    begin
        AddLGA('NG-AB-ANO', 'Aba North', 'NG-AB');
        AddLGA('NG-AB-ASO', 'Aba South', 'NG-AB');
        AddLGA('NG-AB-ARO', 'Arochukwu', 'NG-AB');
        AddLGA('NG-AB-BEN', 'Bende', 'NG-AB');
        AddLGA('NG-AB-IKW', 'Ikwuano', 'NG-AB');
        AddLGA('NG-AB-INN', 'Isiala-Ngwa North', 'NG-AB');
        AddLGA('NG-AB-INS', 'Isiala-Ngwa South', 'NG-AB');
        AddLGA('NG-AB-ISU', 'Isuikwato', 'NG-AB');
        AddLGA('NG-AB-ONW', 'Obi Nwa', 'NG-AB');
        AddLGA('NG-AB-OHA', 'Ohafia', 'NG-AB');
        AddLGA('NG-AB-ONG', 'Osisioma Ngwa', 'NG-AB');
        AddLGA('NG-AB-UGW', 'Ugwunagbo', 'NG-AB');
        AddLGA('NG-AB-UEA', 'Ukwa East', 'NG-AB');
        AddLGA('NG-AB-UWE', 'Ukwa West', 'NG-AB');
        AddLGA('NG-AB-UNO', 'Umuahia North', 'NG-AB');
        AddLGA('NG-AB-USO', 'Umuahia South', 'NG-AB');
        AddLGA('NG-AB-UNE', 'Umu-Neochi', 'NG-AB');
        AddLGA('NG-AD-DEM', 'Demsa', 'NG-AD');
        AddLGA('NG-AD-FUF', 'Fufore', 'NG-AD');
        AddLGA('NG-AD-GAN', 'Ganaye', 'NG-AD');
        AddLGA('NG-AD-GIR', 'Gireri', 'NG-AD');
        AddLGA('NG-AD-GOM', 'Gombi', 'NG-AD');
        AddLGA('NG-AD-GUY', 'Guyuk', 'NG-AD');
        AddLGA('NG-AD-HON', 'Hong', 'NG-AD');
        AddLGA('NG-AD-JAD', 'Jada', 'NG-AD');
        AddLGA('NG-AD-LAM', 'Lamurde', 'NG-AD');
        AddLGA('NG-AD-MAD', 'Madagali', 'NG-AD');
        AddLGA('NG-AD-MAI', 'Maiha', 'NG-AD');
        AddLGA('NG-AD-MBE', 'Mayo-Belwa', 'NG-AD');
        AddLGA('NG-AD-MIC', 'Michika', 'NG-AD');
        AddLGA('NG-AD-MNO', 'Mubi North', 'NG-AD');
        AddLGA('NG-AD-MSO', 'Mubi South', 'NG-AD');
        AddLGA('NG-AD-NUM', 'Numan', 'NG-AD');
        AddLGA('NG-AD-SHE', 'Shelleng', 'NG-AD');
        AddLGA('NG-AD-SON', 'Song', 'NG-AD');
        AddLGA('NG-AD-TOU', 'Toungo', 'NG-AD');
        AddLGA('NG-AD-YNO', 'Yola North', 'NG-AD');
        AddLGA('NG-AD-YSO', 'Yola South', 'NG-AD');
        AddLGA('NG-AK-ABA', 'Abak', 'NG-AK');
        AddLGA('NG-AK-EOB', 'Eastern Obolo', 'NG-AK');
        AddLGA('NG-AK-EKE', 'Eket', 'NG-AK');
        AddLGA('NG-AK-EEK', 'Esit Eket', 'NG-AK');
        AddLGA('NG-AK-EUD', 'Essien Udim', 'NG-AK');
        AddLGA('NG-AK-EE1', 'Etim Ekpo', 'NG-AK');
        AddLGA('NG-AK-ETI', 'Etinan', 'NG-AK');
        AddLGA('NG-AK-IBE', 'Ibeno', 'NG-AK');
        AddLGA('NG-AK-IAS', 'Ibesikpo Asutan', 'NG-AK');
        AddLGA('NG-AK-IIB', 'Ibiono Ibom', 'NG-AK');
        AddLGA('NG-AK-IKA', 'Ika', 'NG-AK');
        AddLGA('NG-AK-IKO', 'Ikono', 'NG-AK');
        AddLGA('NG-AK-IAB', 'Ikot Abasi', 'NG-AK');
        AddLGA('NG-AK-IEK', 'Ikot Ekpene', 'NG-AK');
        AddLGA('NG-AK-INI', 'Ini', 'NG-AK');
        AddLGA('NG-AK-ITU', 'Itu', 'NG-AK');
        AddLGA('NG-AK-MBO', 'Mbo', 'NG-AK');
        AddLGA('NG-AK-MEN', 'Mkpat Enin', 'NG-AK');
        AddLGA('NG-AK-NAT', 'Nsit Atai', 'NG-AK');
        AddLGA('NG-AK-NIB', 'Nsit Ibom', 'NG-AK');
        AddLGA('NG-AK-NUB', 'Nsit Ubium', 'NG-AK');
        AddLGA('NG-AK-OAK', 'Obot Akara', 'NG-AK');
        AddLGA('NG-AK-OKO', 'Okobo', 'NG-AK');
        AddLGA('NG-AK-ONN', 'Onna', 'NG-AK');
        AddLGA('NG-AK-ORO', 'Oron', 'NG-AK');
        AddLGA('NG-AK-OAN', 'Oruk Anam', 'NG-AK');
        AddLGA('NG-AK-UUK', 'Udung Uko', 'NG-AK');
        AddLGA('NG-AK-UKA', 'Ukanafun', 'NG-AK');
        AddLGA('NG-AK-URU', 'Uruan', 'NG-AK');
        AddLGA('NG-AK-UOF', 'Urue-Offong/Oruko', 'NG-AK');
        AddLGA('NG-AK-UYO', 'Uyo', 'NG-AK');
        AddLGA('NG-AN-AGU', 'Aguata', 'NG-AN');
        AddLGA('NG-AN-AEA', 'Anambra East', 'NG-AN');
        AddLGA('NG-AN-AWE', 'Anambra West', 'NG-AN');
        AddLGA('NG-AN-ANA', 'Anaocha', 'NG-AN');
        AddLGA('NG-AN-ANO', 'Awka North', 'NG-AN');
        AddLGA('NG-AN-ASO', 'Awka South', 'NG-AN');
        AddLGA('NG-AN-AYA', 'Ayamelum', 'NG-AN');
        AddLGA('NG-AN-DUN', 'Dunukofia', 'NG-AN');
        AddLGA('NG-AN-EKW', 'Ekwusigo', 'NG-AN');
        AddLGA('NG-AN-INO', 'Idemili North', 'NG-AN');
        AddLGA('NG-AN-ISO', 'Idemili South', 'NG-AN');
        AddLGA('NG-AN-IHI', 'Ihiala', 'NG-AN');
        AddLGA('NG-AN-NJI', 'Njikoka', 'NG-AN');
        AddLGA('NG-AN-NNO', 'Nnewi North', 'NG-AN');
        AddLGA('NG-AN-NSO', 'Nnewi South', 'NG-AN');
        AddLGA('NG-AN-OGB', 'Ogbaru', 'NG-AN');
        AddLGA('NG-AN-ONO', 'Onitsha North', 'NG-AN');
        AddLGA('NG-AN-OSO', 'Onitsha South', 'NG-AN');
        AddLGA('NG-AN-ON1', 'Orumba North', 'NG-AN');
        AddLGA('NG-AN-OS1', 'Orumba South', 'NG-AN');
        AddLGA('NG-AN-OYI', 'Oyi', 'NG-AN');
        AddLGA('NG-BA-ALK', 'Alkaleri', 'NG-BA');
        AddLGA('NG-BA-BAU', 'Bauchi', 'NG-BA');
        AddLGA('NG-BA-BOG', 'Bogoro', 'NG-BA');
        AddLGA('NG-BA-DAM', 'Damban', 'NG-BA');
        AddLGA('NG-BA-DAR', 'Darazo', 'NG-BA');
        AddLGA('NG-BA-DAS', 'Dass', 'NG-BA');
        AddLGA('NG-BA-GLG', 'Gamawa', 'NG-BA');
        AddLGA('NG-BA-GAN', 'Ganjuwa', 'NG-BA');
        AddLGA('NG-BA-GIA', 'Giade', 'NG-BA');
        AddLGA('NG-BA-ITA', 'Itas/Gadau', 'NG-BA');
        AddLGA('NG-BA-JAM', 'Jama''are', 'NG-BA');
        AddLGA('NG-BA-KAT', 'Katagum', 'NG-BA');
        AddLGA('NG-BA-KIR', 'Kirfi', 'NG-BA');
        AddLGA('NG-BA-MIS', 'Misau', 'NG-BA');
        AddLGA('NG-BA-NIN', 'Ningi', 'NG-BA');
        AddLGA('NG-BA-SHI', 'Shira', 'NG-BA');
        AddLGA('NG-BA-TBA', 'Tafawa-Balewa', 'NG-BA');
        AddLGA('NG-BA-TOR', 'Toro', 'NG-BA');
        AddLGA('NG-BA-WAR', 'Warji', 'NG-BA');
        AddLGA('NG-BA-ZAK', 'Zaki', 'NG-BA');
        AddLGA('NG-BY-BRA', 'Brass', 'NG-BY');
        AddLGA('NG-BY-EKE', 'Ekeremor', 'NG-BY');
        AddLGA('NG-BY-KOL', 'Kolokuma/Opokuma', 'NG-BY');
        AddLGA('NG-BY-NEM', 'Nembe', 'NG-BY');
        AddLGA('NG-BY-OGB', 'Ogbia', 'NG-BY');
        AddLGA('NG-BY-SAG', 'Sagbama', 'NG-BY');
        AddLGA('NG-BY-SIJ', 'Southern Ijaw', 'NG-BY');
        AddLGA('NG-BY-YEN', 'Yenegoa', 'NG-BY');
        AddLGA('NG-BE-ADO', 'Ado', 'NG-BE');
        AddLGA('NG-BE-AGA', 'Agatu', 'NG-BE');
    end;

    local procedure SeedLGAChunk2()
    begin
        AddLGA('NG-BE-APA', 'Apa', 'NG-BE');
        AddLGA('NG-BE-BUR', 'Buruku', 'NG-BE');
        AddLGA('NG-BE-GBO', 'Gboko', 'NG-BE');
        AddLGA('NG-BE-GUM', 'Guma', 'NG-BE');
        AddLGA('NG-BE-GEA', 'Gwer East', 'NG-BE');
        AddLGA('NG-BE-GWE', 'Gwer West', 'NG-BE');
        AddLGA('NG-BE-KAL', 'Katsina-Ala', 'NG-BE');
        AddLGA('NG-BE-KON', 'Konshisha', 'NG-BE');
        AddLGA('NG-BE-KWA', 'Kwande', 'NG-BE');
        AddLGA('NG-BE-LOG', 'Logo', 'NG-BE');
        AddLGA('NG-BE-MAK', 'Makurdi', 'NG-BE');
        AddLGA('NG-BE-OBI', 'Obi', 'NG-BE');
        AddLGA('NG-BE-OGB', 'Ogbadibo', 'NG-BE');
        AddLGA('NG-BE-OJU', 'Oju', 'NG-BE');
        AddLGA('NG-BE-OKP', 'Okpokwu', 'NG-BE');
        AddLGA('NG-BE-OHI', 'Ohimini', 'NG-BE');
        AddLGA('NG-BE-OTU', 'Oturkpo', 'NG-BE');
        AddLGA('NG-BE-TAR', 'Tarka', 'NG-BE');
        AddLGA('NG-BE-UKU', 'Ukum', 'NG-BE');
        AddLGA('NG-BE-USH', 'Ushongo', 'NG-BE');
        AddLGA('NG-BE-VAN', 'Vandeikya', 'NG-BE');
        AddLGA('NG-BO-ABA', 'Abadam', 'NG-BO');
        AddLGA('NG-BO-ASK', 'Askira/Uba', 'NG-BO');
        AddLGA('NG-BO-BAM', 'Bama', 'NG-BO');
        AddLGA('NG-BO-BAY', 'Bayo', 'NG-BO');
        AddLGA('NG-BO-BIU', 'Biu', 'NG-BO');
        AddLGA('NG-BO-CHI', 'Chibok', 'NG-BO');
        AddLGA('NG-BO-DAM', 'Damboa', 'NG-BO');
        AddLGA('NG-BO-DIK', 'Dikwa', 'NG-BO');
        AddLGA('NG-BO-GUB', 'Gubio', 'NG-BO');
        AddLGA('NG-BO-GUZ', 'Guzamala', 'NG-BO');
        AddLGA('NG-BO-GWO', 'Gwoza', 'NG-BO');
        AddLGA('NG-BO-HAW', 'Hawul', 'NG-BO');
        AddLGA('NG-BO-JER', 'Jere', 'NG-BO');
        AddLGA('NG-BO-KAG', 'Kaga', 'NG-BO');
        AddLGA('NG-BO-KAL', 'Kala/Balge', 'NG-BO');
        AddLGA('NG-BO-KON', 'Konduga', 'NG-BO');
        AddLGA('NG-BO-KUK', 'Kukawa', 'NG-BO');
        AddLGA('NG-BO-KKU', 'Kwaya Kusar', 'NG-BO');
        AddLGA('NG-BO-MAF', 'Mafa', 'NG-BO');
        AddLGA('NG-BO-MAG', 'Magumeri', 'NG-BO');
        AddLGA('NG-BO-MAI', 'Maiduguri', 'NG-BO');
        AddLGA('NG-BO-MAR', 'Marte', 'NG-BO');
        AddLGA('NG-BO-MOB', 'Mobbar', 'NG-BO');
        AddLGA('NG-BO-MON', 'Monguno', 'NG-BO');
        AddLGA('NG-BO-NGA', 'Ngala', 'NG-BO');
        AddLGA('NG-BO-NG1', 'Nganzai', 'NG-BO');
        AddLGA('NG-BO-SHA', 'Shani', 'NG-BO');
        AddLGA('NG-CR-ABI', 'Abi', 'NG-CR');
        AddLGA('NG-CR-AKA', 'Akamkpa', 'NG-CR');
        AddLGA('NG-CR-AKP', 'Akpabuyo', 'NG-CR');
        AddLGA('NG-CR-BAK', 'Bakassi', 'NG-CR');
        AddLGA('NG-CR-BEK', 'Bekwara', 'NG-CR');
        AddLGA('NG-CR-BIA', 'Biase', 'NG-CR');
        AddLGA('NG-CR-BOK', 'Boki', 'NG-CR');
        AddLGA('NG-CR-CMU', 'Calabar Municipal', 'NG-CR');
        AddLGA('NG-CR-CSO', 'Calabar South', 'NG-CR');
        AddLGA('NG-CR-ETU', 'Etung', 'NG-CR');
        AddLGA('NG-CR-IKO', 'Ikom', 'NG-CR');
        AddLGA('NG-CR-OBA', 'Obanliku', 'NG-CR');
        AddLGA('NG-CR-OBU', 'Obubra', 'NG-CR');
        AddLGA('NG-CR-OB1', 'Obudu', 'NG-CR');
        AddLGA('NG-CR-ODU', 'Odukpani', 'NG-CR');
        AddLGA('NG-CR-OGO', 'Ogoja', 'NG-CR');
        AddLGA('NG-CR-YAK', 'Yakurr', 'NG-CR');
        AddLGA('NG-CR-YAL', 'Yala', 'NG-CR');
        AddLGA('NG-DE-ANO', 'Aniocha North', 'NG-DE');
        AddLGA('NG-DE-ASO', 'Aniocha South', 'NG-DE');
        AddLGA('NG-DE-BOM', 'Bomadi', 'NG-DE');
        AddLGA('NG-DE-BUR', 'Burutu', 'NG-DE');
        AddLGA('NG-DE-EEA', 'Ethiope East', 'NG-DE');
        AddLGA('NG-DE-EWE', 'Ethiope West', 'NG-DE');
        AddLGA('NG-DE-INE', 'Ika North East', 'NG-DE');
        AddLGA('NG-DE-ISO', 'Ika South', 'NG-DE');
        AddLGA('NG-DE-INO', 'Isoko North', 'NG-DE');
        AddLGA('NG-DE-IS1', 'Isoko South', 'NG-DE');
        AddLGA('NG-DE-NEA', 'Ndokwa East', 'NG-DE');
        AddLGA('NG-DE-NWE', 'Ndokwa West', 'NG-DE');
        AddLGA('NG-DE-OKP', 'Okpe', 'NG-DE');
        AddLGA('NG-DE-ONO', 'Oshimili North', 'NG-DE');
        AddLGA('NG-DE-OSO', 'Oshimili South', 'NG-DE');
        AddLGA('NG-DE-PAT', 'Patani', 'NG-DE');
        AddLGA('NG-DE-SAP', 'Sapele', 'NG-DE');
        AddLGA('NG-DE-UDU', 'Udu', 'NG-DE');
        AddLGA('NG-DE-UNO', 'Ughelli North', 'NG-DE');
        AddLGA('NG-DE-USO', 'Ughelli South', 'NG-DE');
        AddLGA('NG-DE-UKW', 'Ukwuani', 'NG-DE');
        AddLGA('NG-DE-UVW', 'Uvwie', 'NG-DE');
        AddLGA('NG-DE-WNO', 'Warri North', 'NG-DE');
        AddLGA('NG-DE-WSO', 'Warri South', 'NG-DE');
        AddLGA('NG-DE-WSW', 'Warri South West', 'NG-DE');
        AddLGA('NG-EB-ABA', 'Abakaliki', 'NG-EB');
        AddLGA('NG-EB-ANO', 'Afikpo North', 'NG-EB');
        AddLGA('NG-EB-ASO', 'Afikpo South', 'NG-EB');
        AddLGA('NG-EB-EBO', 'Ebonyi', 'NG-EB');
        AddLGA('NG-EB-ENO', 'Ezza North', 'NG-EB');
        AddLGA('NG-EB-ESO', 'Ezza South', 'NG-EB');
        AddLGA('NG-EB-IKW', 'Ikwo', 'NG-EB');
        AddLGA('NG-EB-ISH', 'Ishielu', 'NG-EB');
        AddLGA('NG-EB-IVO', 'Ivo', 'NG-EB');
        AddLGA('NG-EB-IZZ', 'Izzi', 'NG-EB');
        AddLGA('NG-EB-OHA', 'Ohaozara', 'NG-EB');
        AddLGA('NG-EB-OH1', 'Ohaukwu', 'NG-EB');
        AddLGA('NG-EB-ONI', 'Onicha', 'NG-EB');
        AddLGA('NG-ED-AED', 'Akoko-Edo', 'NG-ED');
        AddLGA('NG-ED-EGO', 'Egor', 'NG-ED');
        AddLGA('NG-ED-ECE', 'Esan Central', 'NG-ED');
        AddLGA('NG-ED-ENE', 'Esan North East', 'NG-ED');
        AddLGA('NG-ED-ESE', 'Esan South East', 'NG-ED');
        AddLGA('NG-ED-EWE', 'Esan West', 'NG-ED');
        AddLGA('NG-ED-EC1', 'Etsako Central', 'NG-ED');
        AddLGA('NG-ED-EEA', 'Etsako East', 'NG-ED');
        AddLGA('NG-ED-EW1', 'Etsako West', 'NG-ED');
        AddLGA('NG-ED-IGU', 'Igueben', 'NG-ED');
        AddLGA('NG-ED-IOK', 'Ikpoba-Okha', 'NG-ED');
        AddLGA('NG-ED-ORE', 'Oredo', 'NG-ED');
        AddLGA('NG-ED-ORH', 'Orhionmwon', 'NG-ED');
        AddLGA('NG-ED-ONE', 'Ovia North East', 'NG-ED');
        AddLGA('NG-ED-OSW', 'Ovia South West', 'NG-ED');
        AddLGA('NG-ED-OEA', 'Owan East', 'NG-ED');
    end;

    local procedure SeedLGAChunk3()
    begin
        AddLGA('NG-ED-OWE', 'Owan West', 'NG-ED');
        AddLGA('NG-ED-UHU', 'Uhunmwonde', 'NG-ED');
        AddLGA('NG-EK-ADO', 'Ado Ekiti', 'NG-EK');
        AddLGA('NG-EK-AIY', 'Aiyekire', 'NG-EK');
        AddLGA('NG-EK-EFO', 'Efon', 'NG-EK');
        AddLGA('NG-EK-EEA', 'Ekiti East', 'NG-EK');
        AddLGA('NG-EK-ESW', 'Ekiti South West', 'NG-EK');
        AddLGA('NG-EK-EWE', 'Ekiti West', 'NG-EK');
        AddLGA('NG-EK-EMU', 'Emure', 'NG-EK');
        AddLGA('NG-EK-IOS', 'Idosi-Osi', 'NG-EK');
        AddLGA('NG-EK-IJE', 'Ijero', 'NG-EK');
        AddLGA('NG-EK-IKE', 'Ikere', 'NG-EK');
        AddLGA('NG-EK-IKO', 'Ikole', 'NG-EK');
        AddLGA('NG-EK-ILE', 'Ilemeji', 'NG-EK');
        AddLGA('NG-EK-IRE', 'Irepodun/Ifelodun', 'NG-EK');
        AddLGA('NG-EK-ISE', 'Ise/Orun', 'NG-EK');
        AddLGA('NG-EK-MOB', 'Moba', 'NG-EK');
        AddLGA('NG-EK-OYE', 'Oye', 'NG-EK');
        AddLGA('NG-EN-ANI', 'Aninri', 'NG-EN');
        AddLGA('NG-EN-AWG', 'Awgu', 'NG-EN');
        AddLGA('NG-EN-EEA', 'Enugu East', 'NG-EN');
        AddLGA('NG-EN-ENO', 'Enugu North', 'NG-EN');
        AddLGA('NG-EN-ESO', 'Enugu South', 'NG-EN');
        AddLGA('NG-EN-EZE', 'Ezeagu', 'NG-EN');
        AddLGA('NG-EN-IET', 'Igbo-Etiti', 'NG-EN');
        AddLGA('NG-EN-IEN', 'Igbo-Eze North', 'NG-EN');
        AddLGA('NG-EN-IES', 'Igbo-Eze South', 'NG-EN');
        AddLGA('NG-EN-IUZ', 'Isi-Uzo', 'NG-EN');
        AddLGA('NG-EN-NEA', 'Nkanu East', 'NG-EN');
        AddLGA('NG-EN-NWE', 'Nkanu West', 'NG-EN');
        AddLGA('NG-EN-NSU', 'Nsukka', 'NG-EN');
        AddLGA('NG-EN-ORI', 'Oji-River', 'NG-EN');
        AddLGA('NG-EN-UDE', 'Udenu', 'NG-EN');
        AddLGA('NG-EN-UDI', 'Udi', 'NG-EN');
        AddLGA('NG-EN-UUW', 'Uzo-Uwani', 'NG-EN');
        AddLGA('NG-FC-ALG', 'Abaji', 'NG-FC');
        AddLGA('NG-FC-AML', 'Abuja Municipal', 'NG-FC');
        AddLGA('NG-FC-GLG', 'Gwagwalada', 'NG-FC');
        AddLGA('NG-FC-KLG', 'Kuje', 'NG-FC');
        AddLGA('NG-FC-BLG', 'Bwari', 'NG-FC');
        AddLGA('NG-FC-KL1', 'Kwali', 'NG-FC');
        AddLGA('NG-GO-AKK', 'Akko', 'NG-GO');
        AddLGA('NG-GO-BAL', 'Balanga', 'NG-GO');
        AddLGA('NG-GO-BIL', 'Billiri', 'NG-GO');
        AddLGA('NG-GO-DUK', 'Dukku', 'NG-GO');
        AddLGA('NG-GO-FUN', 'Funakaye', 'NG-GO');
        AddLGA('NG-GO-GOM', 'Gombe', 'NG-GO');
        AddLGA('NG-GO-KAL', 'Kaltungo', 'NG-GO');
        AddLGA('NG-GO-KWA', 'Kwami', 'NG-GO');
        AddLGA('NG-GO-NAF', 'Nafada', 'NG-GO');
        AddLGA('NG-GO-SHO', 'Shomgom', 'NG-GO');
        AddLGA('NG-GO-YAM', 'Yamaltu/Deba', 'NG-GO');
        AddLGA('NG-IM-AMB', 'Aboh-Mbaise', 'NG-IM');
        AddLGA('NG-IM-AM1', 'Ahiazu-Mbaise', 'NG-IM');
        AddLGA('NG-IM-EMB', 'Ehime-Mbano', 'NG-IM');
        AddLGA('NG-IM-EZI', 'Ezinihitte', 'NG-IM');
        AddLGA('NG-IM-INO', 'Ideato North', 'NG-IM');
        AddLGA('NG-IM-ISO', 'Ideato South', 'NG-IM');
        AddLGA('NG-IM-IHI', 'Ihitte/Uboma', 'NG-IM');
        AddLGA('NG-IM-IKE', 'Ikeduru', 'NG-IM');
        AddLGA('NG-IM-IMB', 'Isiala Mbano', 'NG-IM');
        AddLGA('NG-IM-ISU', 'Isu', 'NG-IM');
        AddLGA('NG-IM-MBA', 'Mbaitoli', 'NG-IM');
        AddLGA('NG-IM-NOK', 'Ngor-Okpala', 'NG-IM');
        AddLGA('NG-IM-NJA', 'Njaba', 'NG-IM');
        AddLGA('NG-IM-NWA', 'Nwangele', 'NG-IM');
        AddLGA('NG-IM-NKW', 'Nkwerre', 'NG-IM');
        AddLGA('NG-IM-OBO', 'Obowo', 'NG-IM');
        AddLGA('NG-IM-OGU', 'Oguta', 'NG-IM');
        AddLGA('NG-IM-OHA', 'Ohaji/Egbema', 'NG-IM');
        AddLGA('NG-IM-OKI', 'Okigwe', 'NG-IM');
        AddLGA('NG-IM-ORL', 'Orlu', 'NG-IM');
        AddLGA('NG-IM-ORS', 'Orsu', 'NG-IM');
        AddLGA('NG-IM-OEA', 'Oru East', 'NG-IM');
        AddLGA('NG-IM-OWE', 'Oru West', 'NG-IM');
        AddLGA('NG-IM-OMU', 'Owerri Municipal', 'NG-IM');
        AddLGA('NG-IM-ONO', 'Owerri North', 'NG-IM');
        AddLGA('NG-IM-OW1', 'Owerri West', 'NG-IM');
        AddLGA('NG-IM-UNU', 'Unuimo', 'NG-IM');
        AddLGA('NG-JI-AUY', 'Auyo', 'NG-JI');
        AddLGA('NG-JI-BAB', 'Babura', 'NG-JI');
        AddLGA('NG-JI-BKU', 'Birni Kudu', 'NG-JI');
        AddLGA('NG-JI-BIR', 'Biriniwa', 'NG-JI');
        AddLGA('NG-JI-BUJ', 'Buji', 'NG-JI');
        AddLGA('NG-JI-DUT', 'Dutse', 'NG-JI');
        AddLGA('NG-JI-GAG', 'Gagarawa', 'NG-JI');
        AddLGA('NG-JI-GAR', 'Garki', 'NG-JI');
        AddLGA('NG-JI-GUM', 'Gumel', 'NG-JI');
        AddLGA('NG-JI-GUR', 'Guri', 'NG-JI');
        AddLGA('NG-JI-GWA', 'Gwaram', 'NG-JI');
        AddLGA('NG-JI-GWI', 'Gwiwa', 'NG-JI');
        AddLGA('NG-JI-HAD', 'Hadejia', 'NG-JI');
        AddLGA('NG-JI-JAH', 'Jahun', 'NG-JI');
        AddLGA('NG-JI-KHA', 'Kafin Hausa', 'NG-JI');
        AddLGA('NG-JI-KAU', 'Kaugama', 'NG-JI');
        AddLGA('NG-JI-KAZ', 'Kazaure', 'NG-JI');
        AddLGA('NG-JI-KKA', 'Kiri Kasamma', 'NG-JI');
        AddLGA('NG-JI-KIY', 'Kiyawa', 'NG-JI');
        AddLGA('NG-JI-MAI', 'Maigatari', 'NG-JI');
        AddLGA('NG-JI-MMA', 'Malam Madori', 'NG-JI');
        AddLGA('NG-JI-MIG', 'Miga', 'NG-JI');
        AddLGA('NG-JI-RIN', 'Ringim', 'NG-JI');
        AddLGA('NG-JI-RON', 'Roni', 'NG-JI');
        AddLGA('NG-JI-STA', 'Sule-Tankarkar', 'NG-JI');
        AddLGA('NG-JI-TAU', 'Taura', 'NG-JI');
        AddLGA('NG-JI-YAN', 'Yankwashi', 'NG-JI');
        AddLGA('NG-KD-BGW', 'Birnin-Gwari', 'NG-KD');
        AddLGA('NG-KD-CHI', 'Chikun', 'NG-KD');
        AddLGA('NG-KD-GIW', 'Giwa', 'NG-KD');
        AddLGA('NG-KD-IGA', 'Igabi', 'NG-KD');
        AddLGA('NG-KD-IKA', 'Ikara', 'NG-KD');
        AddLGA('NG-KD-JAB', 'Jaba', 'NG-KD');
        AddLGA('NG-KD-JEM', 'Jema''a', 'NG-KD');
        AddLGA('NG-KD-KAC', 'Kachia', 'NG-KD');
        AddLGA('NG-KD-KNO', 'Kaduna North', 'NG-KD');
        AddLGA('NG-KD-KSO', 'Kaduna South', 'NG-KD');
        AddLGA('NG-KD-KAG', 'Kagarko', 'NG-KD');
        AddLGA('NG-KD-KAJ', 'Kajuru', 'NG-KD');
        AddLGA('NG-KD-KLG', 'Kaura', 'NG-KD');
        AddLGA('NG-KD-KAU', 'Kauru', 'NG-KD');
    end;

    local procedure SeedLGAChunk4()
    begin
        AddLGA('NG-KD-KUB', 'Kubau', 'NG-KD');
        AddLGA('NG-KD-KUD', 'Kudan', 'NG-KD');
        AddLGA('NG-KD-LER', 'Lere', 'NG-KD');
        AddLGA('NG-KD-MAR', 'Markafi', 'NG-KD');
        AddLGA('NG-KD-SGA', 'Sabon-Gari', 'NG-KD');
        AddLGA('NG-KD-SAN', 'Sanga', 'NG-KD');
        AddLGA('NG-KD-SOB', 'Soba', 'NG-KD');
        AddLGA('NG-KD-ZKA', 'Zango-Kataf', 'NG-KD');
        AddLGA('NG-KD-ZAR', 'Zaria', 'NG-KD');
        AddLGA('NG-KN-AJI', 'Ajingi', 'NG-KN');
        AddLGA('NG-KN-ALB', 'Albasu', 'NG-KN');
        AddLGA('NG-KN-BAG', 'Bagwai', 'NG-KN');
        AddLGA('NG-KN-BEB', 'Bebeji', 'NG-KN');
        AddLGA('NG-KN-BIC', 'Bichi', 'NG-KN');
        AddLGA('NG-KN-BUN', 'Bunkure', 'NG-KN');
        AddLGA('NG-KN-DAL', 'Dala', 'NG-KN');
        AddLGA('NG-KN-DAM', 'Dambatta', 'NG-KN');
        AddLGA('NG-KN-DKU', 'Dawakin Kudu', 'NG-KN');
        AddLGA('NG-KN-DTO', 'Dawakin Tofa', 'NG-KN');
        AddLGA('NG-KN-DOG', 'Doguwa', 'NG-KN');
        AddLGA('NG-KN-FAG', 'Fagge', 'NG-KN');
        AddLGA('NG-KN-GAB', 'Gabasawa', 'NG-KN');
        AddLGA('NG-KN-GAR', 'Garko', 'NG-KN');
        AddLGA('NG-KN-GMA', 'Garum Mallam', 'NG-KN');
        AddLGA('NG-KN-GAY', 'Gaya', 'NG-KN');
        AddLGA('NG-KN-GEZ', 'Gezawa', 'NG-KN');
        AddLGA('NG-KN-GWA', 'Gwale', 'NG-KN');
        AddLGA('NG-KN-GW1', 'Gwarzo', 'NG-KN');
        AddLGA('NG-KN-KAB', 'Kabo', 'NG-KN');
        AddLGA('NG-KN-KMU', 'Kano Municipal', 'NG-KN');
        AddLGA('NG-KN-KAR', 'Karaye', 'NG-KN');
        AddLGA('NG-KN-KIB', 'Kibiya', 'NG-KN');
        AddLGA('NG-KN-KIR', 'Kiru', 'NG-KN');
        AddLGA('NG-KN-KUM', 'Kumbotso', 'NG-KN');
        AddLGA('NG-KN-KUN', 'Kunchi', 'NG-KN');
        AddLGA('NG-KN-KUR', 'Kura', 'NG-KN');
        AddLGA('NG-KN-MAD', 'Madobi', 'NG-KN');
        AddLGA('NG-KN-MAK', 'Makoda', 'NG-KN');
        AddLGA('NG-KN-MIN', 'Minjibir', 'NG-KN');
        AddLGA('NG-KN-NAS', 'Nasarawa', 'NG-KN');
        AddLGA('NG-KN-RAN', 'Rano', 'NG-KN');
        AddLGA('NG-KN-RGA', 'Rimin Gado', 'NG-KN');
        AddLGA('NG-KN-ROG', 'Rogo', 'NG-KN');
        AddLGA('NG-KN-SHA', 'Shanono', 'NG-KN');
        AddLGA('NG-KN-SUM', 'Sumaila', 'NG-KN');
        AddLGA('NG-KN-TAK', 'Takai', 'NG-KN');
        AddLGA('NG-KN-TAR', 'Tarauni', 'NG-KN');
        AddLGA('NG-KN-TOF', 'Tofa', 'NG-KN');
        AddLGA('NG-KN-TSA', 'Tsanyawa', 'NG-KN');
        AddLGA('NG-KN-TWA', 'Tudun Wada', 'NG-KN');
        AddLGA('NG-KN-UNG', 'Ungogo', 'NG-KN');
        AddLGA('NG-KN-WAR', 'Warawa', 'NG-KN');
        AddLGA('NG-KN-WUD', 'Wudil', 'NG-KN');
        AddLGA('NG-KT-BAK', 'Bakori', 'NG-KT');
        AddLGA('NG-KT-BAT', 'Batagarawa', 'NG-KT');
        AddLGA('NG-KT-BA1', 'Batsari', 'NG-KT');
        AddLGA('NG-KT-BAU', 'Baure', 'NG-KT');
        AddLGA('NG-KT-BIN', 'Bindawa', 'NG-KT');
        AddLGA('NG-KT-CHA', 'Charanchi', 'NG-KT');
        AddLGA('NG-KT-DAN', 'Dandume', 'NG-KT');
        AddLGA('NG-KT-DA1', 'Danja', 'NG-KT');
        AddLGA('NG-KT-DMU', 'Dan Musa', 'NG-KT');
        AddLGA('NG-KT-DAU', 'Daura', 'NG-KT');
        AddLGA('NG-KT-DUT', 'Dutsi', 'NG-KT');
        AddLGA('NG-KT-DMA', 'Dutsin-Ma', 'NG-KT');
        AddLGA('NG-KT-FAS', 'Faskari', 'NG-KT');
        AddLGA('NG-KT-FUN', 'Funtua', 'NG-KT');
        AddLGA('NG-KT-ING', 'Ingawa', 'NG-KT');
        AddLGA('NG-KT-JIB', 'Jibia', 'NG-KT');
        AddLGA('NG-KT-KAF', 'Kafur', 'NG-KT');
        AddLGA('NG-KT-KAI', 'Kaita', 'NG-KT');
        AddLGA('NG-KT-KAN', 'Kankara', 'NG-KT');
        AddLGA('NG-KT-KA1', 'Kankia', 'NG-KT');
        AddLGA('NG-KT-KAT', 'Katsina', 'NG-KT');
        AddLGA('NG-KT-KUR', 'Kurfi', 'NG-KT');
        AddLGA('NG-KT-KUS', 'Kusada', 'NG-KT');
        AddLGA('NG-KT-MAI', 'Mai''Adua', 'NG-KT');
        AddLGA('NG-KT-MAL', 'Malumfashi', 'NG-KT');
        AddLGA('NG-KT-MAN', 'Mani', 'NG-KT');
        AddLGA('NG-KT-MAS', 'Mashi', 'NG-KT');
        AddLGA('NG-KT-MAT', 'Matazuu', 'NG-KT');
        AddLGA('NG-KT-MUS', 'Musawa', 'NG-KT');
        AddLGA('NG-KT-RIM', 'Rimi', 'NG-KT');
        AddLGA('NG-KT-SAB', 'Sabuwa', 'NG-KT');
        AddLGA('NG-KT-SAF', 'Safana', 'NG-KT');
        AddLGA('NG-KT-SAN', 'Sandamu', 'NG-KT');
        AddLGA('NG-KT-ZAN', 'Zango', 'NG-KT');
        AddLGA('NG-KE-ALE', 'Aleiro', 'NG-KE');
        AddLGA('NG-KE-ADA', 'Arewa-Dandi', 'NG-KE');
        AddLGA('NG-KE-ARG', 'Argungu', 'NG-KE');
        AddLGA('NG-KE-AUG', 'Augie', 'NG-KE');
        AddLGA('NG-KE-BAG', 'Bagudo', 'NG-KE');
        AddLGA('NG-KE-BKE', 'Birnin Kebbi', 'NG-KE');
        AddLGA('NG-KE-BUN', 'Bunza', 'NG-KE');
        AddLGA('NG-KE-DAN', 'Dandi', 'NG-KE');
        AddLGA('NG-KE-FAK', 'Fakai', 'NG-KE');
        AddLGA('NG-KE-GWA', 'Gwandu', 'NG-KE');
        AddLGA('NG-KE-JEG', 'Jega', 'NG-KE');
        AddLGA('NG-KE-KAL', 'Kalgo', 'NG-KE');
        AddLGA('NG-KE-KOK', 'Koko/Besse', 'NG-KE');
        AddLGA('NG-KE-MAI', 'Maiyama', 'NG-KE');
        AddLGA('NG-KE-NGA', 'Ngaski', 'NG-KE');
        AddLGA('NG-KE-SAK', 'Sakaba', 'NG-KE');
        AddLGA('NG-KE-SHA', 'Shanga', 'NG-KE');
        AddLGA('NG-KE-SUR', 'Suru', 'NG-KE');
        AddLGA('NG-KE-WAS', 'Wasagu/Danko', 'NG-KE');
        AddLGA('NG-KE-YAU', 'Yauri', 'NG-KE');
        AddLGA('NG-KE-ZUR', 'Zuru', 'NG-KE');
        AddLGA('NG-KO-ADA', 'Adavi', 'NG-KO');
        AddLGA('NG-KO-AJA', 'Ajaokuta', 'NG-KO');
        AddLGA('NG-KO-ANK', 'Ankpa', 'NG-KO');
        AddLGA('NG-KO-BAS', 'Bassa', 'NG-KO');
        AddLGA('NG-KO-DEK', 'Dekina', 'NG-KO');
        AddLGA('NG-KO-IBA', 'Ibaji', 'NG-KO');
        AddLGA('NG-KO-IDA', 'Idah', 'NG-KO');
        AddLGA('NG-KO-IOD', 'Igalamela-Odolu', 'NG-KO');
        AddLGA('NG-KO-IJU', 'Ijumu', 'NG-KO');
        AddLGA('NG-KO-KAB', 'Kabba/Bunu', 'NG-KO');
        AddLGA('NG-KO-KOG', 'Kogi', 'NG-KO');
        AddLGA('NG-KO-LOK', 'Lokoja', 'NG-KO');
    end;

    local procedure SeedLGAChunk5()
    begin
        AddLGA('NG-KO-MMU', 'Mopa-Muro', 'NG-KO');
        AddLGA('NG-KO-OFU', 'Ofu', 'NG-KO');
        AddLGA('NG-KO-OGO', 'Ogori/Mangongo', 'NG-KO');
        AddLGA('NG-KO-OKE', 'Okehi', 'NG-KO');
        AddLGA('NG-KO-OK1', 'Okene', 'NG-KO');
        AddLGA('NG-KO-OLA', 'Olamabolo', 'NG-KO');
        AddLGA('NG-KO-OMA', 'Omala', 'NG-KO');
        AddLGA('NG-KO-YEA', 'Yagba East', 'NG-KO');
        AddLGA('NG-KO-YWE', 'Yagba West', 'NG-KO');
        AddLGA('NG-KW-ASA', 'Asa', 'NG-KW');
        AddLGA('NG-KW-BAR', 'Baruten', 'NG-KW');
        AddLGA('NG-KW-EDU', 'Edu', 'NG-KW');
        AddLGA('NG-KW-EKI', 'Ekiti', 'NG-KW');
        AddLGA('NG-KW-IFE', 'Ifelodun', 'NG-KW');
        AddLGA('NG-KW-IEA', 'Ilorin East', 'NG-KW');
        AddLGA('NG-KW-ISL', 'Ilorin South', 'NG-KW');
        AddLGA('NG-KW-IWE', 'Ilorin West', 'NG-KW');
        AddLGA('NG-KW-IRE', 'Irepodun', 'NG-KW');
        AddLGA('NG-KW-ISI', 'Isin', 'NG-KW');
        AddLGA('NG-KW-KAI', 'Kaiama', 'NG-KW');
        AddLGA('NG-KW-MOR', 'Moro', 'NG-KW');
        AddLGA('NG-KW-OFF', 'Offa', 'NG-KW');
        AddLGA('NG-KW-OER', 'Oke-Ero', 'NG-KW');
        AddLGA('NG-KW-OYU', 'Oyun', 'NG-KW');
        AddLGA('NG-KW-PAT', 'Pategi', 'NG-KW');
        AddLGA('NG-LA-AGE', 'Agege', 'NG-LA');
        AddLGA('NG-LA-AIF', 'Ajeromi-Ifelodun', 'NG-LA');
        AddLGA('NG-LA-ALI', 'Alimosho', 'NG-LA');
        AddLGA('NG-LA-AOD', 'Amuwo-Odofin', 'NG-LA');
        AddLGA('NG-LA-APA', 'Apapa', 'NG-LA');
        AddLGA('NG-LA-BAD', 'Badagry', 'NG-LA');
        AddLGA('NG-LA-EPE', 'Epe', 'NG-LA');
        AddLGA('NG-LA-EOS', 'Eti-Osa', 'NG-LA');
        AddLGA('NG-LA-IBE', 'Ibeju/Lekki', 'NG-LA');
        AddLGA('NG-LA-IIJ', 'Ifako-Ijaye', 'NG-LA');
        AddLGA('NG-LA-IKE', 'Ikeja', 'NG-LA');
        AddLGA('NG-LA-IKO', 'Ikorodu', 'NG-LA');
        AddLGA('NG-LA-KOS', 'Kosofe', 'NG-LA');
        AddLGA('NG-LA-LIS', 'Lagos Island', 'NG-LA');
        AddLGA('NG-LA-LMA', 'Lagos Mainland', 'NG-LA');
        AddLGA('NG-LA-MUS', 'Mushin', 'NG-LA');
        AddLGA('NG-LA-OJO', 'Ojo', 'NG-LA');
        AddLGA('NG-LA-OIS', 'Oshodi-Isolo', 'NG-LA');
        AddLGA('NG-LA-SHO', 'Shomolu', 'NG-LA');
        AddLGA('NG-LA-SUR', 'Surulere', 'NG-LA');
        AddLGA('NG-NA-AKW', 'Akwanga', 'NG-NA');
        AddLGA('NG-NA-AWE', 'Awe', 'NG-NA');
        AddLGA('NG-NA-DOM', 'Doma', 'NG-NA');
        AddLGA('NG-NA-KAR', 'Karu', 'NG-NA');
        AddLGA('NG-NA-KEA', 'Keana', 'NG-NA');
        AddLGA('NG-NA-KEF', 'Keffi', 'NG-NA');
        AddLGA('NG-NA-KOK', 'Kokona', 'NG-NA');
        AddLGA('NG-NA-LAF', 'Lafia', 'NG-NA');
        AddLGA('NG-NA-NAS', 'Nasarawa', 'NG-NA');
        AddLGA('NG-NA-NEG', 'Nasarawa-Eggon', 'NG-NA');
        AddLGA('NG-NA-OBI', 'Obi', 'NG-NA');
        AddLGA('NG-NA-TOT', 'Toto', 'NG-NA');
        AddLGA('NG-NA-WAM', 'Wamba', 'NG-NA');
        AddLGA('NG-NI-AGA', 'Agaie', 'NG-NI');
        AddLGA('NG-NI-AGW', 'Agwara', 'NG-NI');
        AddLGA('NG-NI-BID', 'Bida', 'NG-NI');
        AddLGA('NG-NI-BOR', 'Borgu', 'NG-NI');
        AddLGA('NG-NI-BOS', 'Bosso', 'NG-NI');
        AddLGA('NG-NI-CHA', 'Chanchaga', 'NG-NI');
        AddLGA('NG-NI-EDA', 'Edati', 'NG-NI');
        AddLGA('NG-NI-GBA', 'Gbako', 'NG-NI');
        AddLGA('NG-NI-GUR', 'Gurara', 'NG-NI');
        AddLGA('NG-NI-KAT', 'Katcha', 'NG-NI');
        AddLGA('NG-NI-KON', 'Kontagora', 'NG-NI');
        AddLGA('NG-NI-LAP', 'Lapai', 'NG-NI');
        AddLGA('NG-NI-LAV', 'Lavun', 'NG-NI');
        AddLGA('NG-NI-MAG', 'Magama', 'NG-NI');
        AddLGA('NG-NI-MAR', 'Mariga', 'NG-NI');
        AddLGA('NG-NI-MAS', 'Mashegu', 'NG-NI');
        AddLGA('NG-NI-MOK', 'Mokwa', 'NG-NI');
        AddLGA('NG-NI-MUY', 'Muya', 'NG-NI');
        AddLGA('NG-NI-PAI', 'Pailoro', 'NG-NI');
        AddLGA('NG-NI-RAF', 'Rafi', 'NG-NI');
        AddLGA('NG-NI-RIJ', 'Rijau', 'NG-NI');
        AddLGA('NG-NI-SHI', 'Shiroro', 'NG-NI');
        AddLGA('NG-NI-SUL', 'Suleja', 'NG-NI');
        AddLGA('NG-NI-TAF', 'Tafa', 'NG-NI');
        AddLGA('NG-NI-WUS', 'Wushishi', 'NG-NI');
        AddLGA('NG-OG-ANO', 'Abeokuta North', 'NG-OG');
        AddLGA('NG-OG-ASO', 'Abeokuta South', 'NG-OG');
        AddLGA('NG-OG-AOD', 'Ado-Odo/Ota', 'NG-OG');
        AddLGA('NG-OG-ENO', 'Egbado North', 'NG-OG');
        AddLGA('NG-OG-ESO', 'Egbado South', 'NG-OG');
        AddLGA('NG-OG-EWE', 'Ewekoro', 'NG-OG');
        AddLGA('NG-OG-IFO', 'Ifo', 'NG-OG');
        AddLGA('NG-OG-IEA', 'Ijebu East', 'NG-OG');
        AddLGA('NG-OG-INO', 'Ijebu North', 'NG-OG');
        AddLGA('NG-OG-INE', 'Ijebu North East', 'NG-OG');
        AddLGA('NG-OG-IOD', 'Ijebu Ode', 'NG-OG');
        AddLGA('NG-OG-IKE', 'Ikenne', 'NG-OG');
        AddLGA('NG-OG-IAF', 'Imeko-Afon', 'NG-OG');
        AddLGA('NG-OG-IPO', 'Ipokia', 'NG-OG');
        AddLGA('NG-OG-OOW', 'Obafemi-Owode', 'NG-OG');
        AddLGA('NG-OG-OWA', 'Ogun Waterside', 'NG-OG');
        AddLGA('NG-OG-ODE', 'Odeda', 'NG-OG');
        AddLGA('NG-OG-ODO', 'Odogbolu', 'NG-OG');
        AddLGA('NG-OG-RNO', 'Remo North', 'NG-OG');
        AddLGA('NG-OG-SHA', 'Shagamu', 'NG-OG');
        AddLGA('NG-ON-ANE', 'Akoko North East', 'NG-ON');
        AddLGA('NG-ON-ANW', 'Akoko North West', 'NG-ON');
        AddLGA('NG-ON-ASA', 'Akoko South East', 'NG-ON');
        AddLGA('NG-ON-ASW', 'Akoko South West', 'NG-ON');
        AddLGA('NG-ON-ANO', 'Akure North', 'NG-ON');
        AddLGA('NG-ON-ASO', 'Akure South', 'NG-ON');
        AddLGA('NG-ON-EOD', 'Ese-Odo', 'NG-ON');
        AddLGA('NG-ON-IDA', 'Idanre', 'NG-ON');
        AddLGA('NG-ON-IFE', 'Ifedore', 'NG-ON');
        AddLGA('NG-ON-ILA', 'Ilaje', 'NG-ON');
        AddLGA('NG-ON-IOO', 'Ile-Oluji-Okeigbo', 'NG-ON');
        AddLGA('NG-ON-IRE', 'Irele', 'NG-ON');
        AddLGA('NG-ON-ODI', 'Odigbo', 'NG-ON');
        AddLGA('NG-ON-OKI', 'Okitipupa', 'NG-ON');
        AddLGA('NG-ON-OEA', 'Ondo East', 'NG-ON');
        AddLGA('NG-ON-OWE', 'Ondo West', 'NG-ON');
        AddLGA('NG-ON-OSE', 'Ose', 'NG-ON');
    end;

    local procedure SeedLGAChunk6()
    begin
        AddLGA('NG-ON-OWO', 'Owo', 'NG-ON');
        AddLGA('NG-OS-AIY', 'Aiyedade', 'NG-OS');
        AddLGA('NG-OS-AI1', 'Aiyedire', 'NG-OS');
        AddLGA('NG-OS-AEA', 'Atakumosa East', 'NG-OS');
        AddLGA('NG-OS-AWE', 'Atakumosa West', 'NG-OS');
        AddLGA('NG-OS-BOL', 'Boluwaduro', 'NG-OS');
        AddLGA('NG-OS-BOR', 'Boripe', 'NG-OS');
        AddLGA('NG-OS-ENO', 'Ede North', 'NG-OS');
        AddLGA('NG-OS-ESO', 'Ede South', 'NG-OS');
        AddLGA('NG-OS-EGB', 'Egbedore', 'NG-OS');
        AddLGA('NG-OS-EJI', 'Ejigbo', 'NG-OS');
        AddLGA('NG-OS-ICE', 'Ife Central', 'NG-OS');
        AddLGA('NG-OS-IEA', 'Ife East', 'NG-OS');
        AddLGA('NG-OS-INO', 'Ife North', 'NG-OS');
        AddLGA('NG-OS-ISO', 'Ife South', 'NG-OS');
        AddLGA('NG-OS-IFE', 'Ifedayo', 'NG-OS');
        AddLGA('NG-OS-IF1', 'Ifelodun', 'NG-OS');
        AddLGA('NG-OS-ILA', 'Ila', 'NG-OS');
        AddLGA('NG-OS-IE1', 'Ilesha East', 'NG-OS');
        AddLGA('NG-OS-IWE', 'Ilesha West', 'NG-OS');
        AddLGA('NG-OS-IRE', 'Irepodun', 'NG-OS');
        AddLGA('NG-OS-IR1', 'Irewole', 'NG-OS');
        AddLGA('NG-OS-IS1', 'Isokan', 'NG-OS');
        AddLGA('NG-OS-IWO', 'Iwo', 'NG-OS');
        AddLGA('NG-OS-OBO', 'Obokun', 'NG-OS');
        AddLGA('NG-OS-OOT', 'Odo-Otin', 'NG-OS');
        AddLGA('NG-OS-OOL', 'Ola-Oluwa', 'NG-OS');
        AddLGA('NG-OS-OLO', 'Olorunda', 'NG-OS');
        AddLGA('NG-OS-ORI', 'Oriade', 'NG-OS');
        AddLGA('NG-OS-ORO', 'Orolu', 'NG-OS');
        AddLGA('NG-OS-OSO', 'Osogbo', 'NG-OS');
        AddLGA('NG-OY-AFI', 'Afijio', 'NG-OY');
        AddLGA('NG-OY-AKI', 'Akinyele', 'NG-OY');
        AddLGA('NG-OY-ATI', 'Atiba', 'NG-OY');
        AddLGA('NG-OY-AT1', 'Atisbo', 'NG-OY');
        AddLGA('NG-OY-EGB', 'Egbeda', 'NG-OY');
        AddLGA('NG-OY-ICE', 'Ibadan Central', 'NG-OY');
        AddLGA('NG-OY-INO', 'Ibadan North', 'NG-OY');
        AddLGA('NG-OY-INE', 'Ibadan North East', 'NG-OY');
        AddLGA('NG-OY-INW', 'Ibadan North West', 'NG-OY');
        AddLGA('NG-OY-ISE', 'Ibadan South East', 'NG-OY');
        AddLGA('NG-OY-ISW', 'Ibadan South West', 'NG-OY');
        AddLGA('NG-OY-IC1', 'Ibarapa Central', 'NG-OY');
        AddLGA('NG-OY-IEA', 'Ibarapa East', 'NG-OY');
        AddLGA('NG-OY-IN1', 'Ibarapa North', 'NG-OY');
        AddLGA('NG-OY-IDO', 'Ido', 'NG-OY');
        AddLGA('NG-OY-IRE', 'Irepo', 'NG-OY');
        AddLGA('NG-OY-IS1', 'Iseyin', 'NG-OY');
        AddLGA('NG-OY-ITE', 'Itesiwaju', 'NG-OY');
        AddLGA('NG-OY-IWA', 'Iwajowa', 'NG-OY');
        AddLGA('NG-OY-KAJ', 'Kajola', 'NG-OY');
        AddLGA('NG-OY-LAG', 'Lagelu', 'NG-OY');
        AddLGA('NG-OY-ONO', 'Ogbomosho North', 'NG-OY');
        AddLGA('NG-OY-OSO', 'Ogbomosho South', 'NG-OY');
        AddLGA('NG-OY-OGO', 'Ogo Oluwa', 'NG-OY');
        AddLGA('NG-OY-OLO', 'Olorunsogo', 'NG-OY');
        AddLGA('NG-OY-OLU', 'Oluyole', 'NG-OY');
        AddLGA('NG-OY-OAR', 'Ona-Ara', 'NG-OY');
        AddLGA('NG-OY-ORE', 'Orelope', 'NG-OY');
        AddLGA('NG-OY-ORI', 'Ori Ire', 'NG-OY');
        AddLGA('NG-OY-OEA', 'Oyo East', 'NG-OY');
        AddLGA('NG-OY-OWE', 'Oyo West', 'NG-OY');
        AddLGA('NG-OY-SEA', 'Saki East', 'NG-OY');
        AddLGA('NG-OY-SWE', 'Saki West', 'NG-OY');
        AddLGA('NG-OY-SUR', 'Surulere', 'NG-OY');
        AddLGA('NG-PL-BLA', 'Barikin Ladi', 'NG-PL');
        AddLGA('NG-PL-BA1', 'Bassa', 'NG-PL');
        AddLGA('NG-PL-BOK', 'Bokkos', 'NG-PL');
        AddLGA('NG-PL-JEA', 'Jos East', 'NG-PL');
        AddLGA('NG-PL-JNO', 'Jos North', 'NG-PL');
        AddLGA('NG-PL-JSO', 'Jos South', 'NG-PL');
        AddLGA('NG-PL-KAN', 'Kanam', 'NG-PL');
        AddLGA('NG-PL-KA1', 'Kanke', 'NG-PL');
        AddLGA('NG-PL-LNO', 'Langtang North', 'NG-PL');
        AddLGA('NG-PL-LSO', 'Langtang South', 'NG-PL');
        AddLGA('NG-PL-MAN', 'Mangu', 'NG-PL');
        AddLGA('NG-PL-MIK', 'Mikang', 'NG-PL');
        AddLGA('NG-PL-PAN', 'Pankshin', 'NG-PL');
        AddLGA('NG-PL-QPA', 'Qua''an Pan', 'NG-PL');
        AddLGA('NG-PL-RIY', 'Riyom', 'NG-PL');
        AddLGA('NG-PL-SHE', 'Shendam', 'NG-PL');
        AddLGA('NG-PL-WAS', 'Wase', 'NG-PL');
        AddLGA('NG-RI-ABU', 'Abua/Odual', 'NG-RI');
        AddLGA('NG-RI-AEA', 'Ahoada East', 'NG-RI');
        AddLGA('NG-RI-AWE', 'Ahoada West', 'NG-RI');
        AddLGA('NG-RI-ATO', 'Akuku Toru', 'NG-RI');
        AddLGA('NG-RI-AND', 'Andoni', 'NG-RI');
        AddLGA('NG-RI-AT1', 'Asari-Toru', 'NG-RI');
        AddLGA('NG-RI-BON', 'Bonny', 'NG-RI');
        AddLGA('NG-RI-DEG', 'Degema', 'NG-RI');
        AddLGA('NG-RI-EMO', 'Emohua', 'NG-RI');
        AddLGA('NG-RI-ELE', 'Eleme', 'NG-RI');
        AddLGA('NG-RI-ETC', 'Etche', 'NG-RI');
        AddLGA('NG-RI-GOK', 'Gokana', 'NG-RI');
        AddLGA('NG-RI-IKW', 'Ikwerre', 'NG-RI');
        AddLGA('NG-RI-KHA', 'Khana', 'NG-RI');
        AddLGA('NG-RI-OBI', 'Obia/Akpor', 'NG-RI');
        AddLGA('NG-RI-OGB', 'Ogba/Egbema/Ndoni', 'NG-RI');
        AddLGA('NG-RI-OGU', 'Ogu/Bolo', 'NG-RI');
        AddLGA('NG-RI-OKR', 'Okrika', 'NG-RI');
        AddLGA('NG-RI-OMU', 'Omumma', 'NG-RI');
        AddLGA('NG-RI-OPO', 'Opobo/Nkoro', 'NG-RI');
        AddLGA('NG-RI-OYI', 'Oyigbo', 'NG-RI');
        AddLGA('NG-RI-PHA', 'Port Harcourt', 'NG-RI');
        AddLGA('NG-RI-TAI', 'Tai', 'NG-RI');
        AddLGA('NG-SO-BIN', 'Binji', 'NG-SO');
        AddLGA('NG-SO-BOD', 'Bodinga', 'NG-SO');
        AddLGA('NG-SO-DSH', 'Dange-Shuni', 'NG-SO');
        AddLGA('NG-SO-GAD', 'Gada', 'NG-SO');
        AddLGA('NG-SO-GOR', 'Goronyo', 'NG-SO');
        AddLGA('NG-SO-GUD', 'Gudu', 'NG-SO');
        AddLGA('NG-SO-GAW', 'Gwadabawa', 'NG-SO');
        AddLGA('NG-SO-ILL', 'Illela', 'NG-SO');
        AddLGA('NG-SO-ISA', 'Isa', 'NG-SO');
        AddLGA('NG-SO-KWA', 'Kware', 'NG-SO');
        AddLGA('NG-SO-KEB', 'Kebbe', 'NG-SO');
        AddLGA('NG-SO-RAB', 'Rabah', 'NG-SO');
        AddLGA('NG-SO-SBI', 'Sabon Birni', 'NG-SO');
        AddLGA('NG-SO-SHA', 'Shagari', 'NG-SO');
        AddLGA('NG-SO-SIL', 'Silame', 'NG-SO');
    end;

    local procedure SeedLGAChunk7()
    begin
        AddLGA('NG-SO-SNO', 'Sokoto North', 'NG-SO');
        AddLGA('NG-SO-SSO', 'Sokoto South', 'NG-SO');
        AddLGA('NG-SO-TAM', 'Tambuwal', 'NG-SO');
        AddLGA('NG-SO-TQN', 'Tangaza', 'NG-SO');
        AddLGA('NG-SO-TUR', 'Tureta', 'NG-SO');
        AddLGA('NG-SO-WAM', 'Wamako', 'NG-SO');
        AddLGA('NG-SO-WUR', 'Wurno', 'NG-SO');
        AddLGA('NG-SO-YAB', 'Yabo', 'NG-SO');
        AddLGA('NG-TA-AKO', 'Ardo-Kola', 'NG-TA');
        AddLGA('NG-TA-BAL', 'Bali', 'NG-TA');
        AddLGA('NG-TA-DON', 'Donga', 'NG-TA');
        AddLGA('NG-TA-GAS', 'Gashaka', 'NG-TA');
        AddLGA('NG-TA-GSS', 'Gassol', 'NG-TA');
        AddLGA('NG-TA-IBI', 'Ibi', 'NG-TA');
        AddLGA('NG-TA-JAL', 'Jalingo', 'NG-TA');
        AddLGA('NG-TA-KLA', 'Karin-Lamido', 'NG-TA');
        AddLGA('NG-TA-KUR', 'Kurmi', 'NG-TA');
        AddLGA('NG-TA-LAU', 'Lau', 'NG-TA');
        AddLGA('NG-TA-SAR', 'Sardauna', 'NG-TA');
        AddLGA('NG-TA-TAK', 'Takum', 'NG-TA');
        AddLGA('NG-TA-USS', 'Ussa', 'NG-TA');
        AddLGA('NG-TA-WUK', 'Wukari', 'NG-TA');
        AddLGA('NG-TA-YOR', 'Yorro', 'NG-TA');
        AddLGA('NG-TA-ZIN', 'Zing', 'NG-TA');
        AddLGA('NG-YO-BAD', 'Bade', 'NG-YO');
        AddLGA('NG-YO-BUR', 'Bursari', 'NG-YO');
        AddLGA('NG-YO-DAM', 'Damaturu', 'NG-YO');
        AddLGA('NG-YO-FIK', 'Fika', 'NG-YO');
        AddLGA('NG-YO-FUN', 'Fune', 'NG-YO');
        AddLGA('NG-YO-GEI', 'Geidam', 'NG-YO');
        AddLGA('NG-YO-GUJ', 'Gujba', 'NG-YO');
        AddLGA('NG-YO-GUL', 'Gulani', 'NG-YO');
        AddLGA('NG-YO-JAK', 'Jakusko', 'NG-YO');
        AddLGA('NG-YO-KAR', 'Karasuwa', 'NG-YO');
        AddLGA('NG-YO-KA1', 'Karawa', 'NG-YO');
        AddLGA('NG-YO-MAC', 'Machina', 'NG-YO');
        AddLGA('NG-YO-NAN', 'Nangere', 'NG-YO');
        AddLGA('NG-YO-NGU', 'Nguru', 'NG-YO');
        AddLGA('NG-YO-POT', 'Potiskum', 'NG-YO');
        AddLGA('NG-YO-TAR', 'Tarmua', 'NG-YO');
        AddLGA('NG-YO-YUN', 'Yunusari', 'NG-YO');
        AddLGA('NG-YO-YUS', 'Yusufari', 'NG-YO');
        AddLGA('NG-ZA-ANK', 'Anka', 'NG-ZA');
        AddLGA('NG-ZA-BAK', 'Bakura', 'NG-ZA');
        AddLGA('NG-ZA-BMA', 'Birnin Magaji', 'NG-ZA');
        AddLGA('NG-ZA-BUK', 'Bukkuyum', 'NG-ZA');
        AddLGA('NG-ZA-BUN', 'Bungudu', 'NG-ZA');
        AddLGA('NG-ZA-GUM', 'Gummi', 'NG-ZA');
        AddLGA('NG-ZA-GUS', 'Gusau', 'NG-ZA');
        AddLGA('NG-ZA-KNA', 'Kaura Namoda', 'NG-ZA');
        AddLGA('NG-ZA-MAR', 'Maradun', 'NG-ZA');
        AddLGA('NG-ZA-MA1', 'Maru', 'NG-ZA');
        AddLGA('NG-ZA-SHI', 'Shinkafi', 'NG-ZA');
        AddLGA('NG-ZA-TMA', 'Talata Mafara', 'NG-ZA');
        AddLGA('NG-ZA-TSA', 'Tsafe', 'NG-ZA');
        AddLGA('NG-ZA-ZUR', 'Zurmi', 'NG-ZA');
    end;
}
